export const GET_EVENT_DATA_REQUEST = 'GET_EVENT_DATA_REQUEST';
export const POST_EVENT_DATA_REQUEST = 'POST_EVENT_DATA_REQUEST';
export const PUT_EVENT_DATA_REQUEST = 'PUT_EVENT_DATA_REQUEST';
export const DELETE_EVENT_DATA_REQUEST = 'DELETE_EVENT_DATA_REQUEST';
export const RECEIVE_EVENT_DATA = 'RECEIVE_EVENT_DATA';
export const EVENT_URL = 'http://crabfactory.net/todo-api/event/';

export const GET_EVENT_CLASS_DATA_REQUEST = 'GET_EVENT_CLASS_DATA_REQUEST';
export const POST_EVENT_CLASS_DATA_REQUEST = 'POST_EVENT_CLASS_DATA_REQUEST';
export const PUT_EVENT_CLASS_DATA_REQUEST = 'PUT_EVENT_CLASS_DATA_REQUEST';
export const DELETE_EVENT_CLASS_DATA_REQUEST = 'DELETE_EVENT_CLASS_DATA_REQUEST';
export const RECEIVE_EVENT_CLASS_DATA = 'RECEIVE_EVENT_CLASS_DATA';
export const SELECT_EVENT_CLASS = 'SELECT_EVENT"CLASS';
export const EVENT_CLASS_URL = 'http://crabfactory.net/todo-api/event-class/';
